version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taskflow_db
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: